# Uncomment this line to define a global platform for your project
# platform :ios, ‘7.0’

target 'FunctionReactivePixels' do

pod 'ReactiveCocoa', '~> 2.5'
pod 'libextobjc', '~> 0.4.1'
pod '500px-iOS-api', '~> 1.0.5'
pod 'SVProgressHUD', '~> 1.1.3'

end

target 'FunctionReactivePixelsTests' do

end

